# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4394fbae58d4c642ce2bfa24fd6c6c9332d465945f8bb71cb964de7c4125637bb6ef7ff897b7649fe748315f03db31772729355371d1f6d2faa1e240beaadb31

test:
  secret_key_base: 55f3acf43a6662a1414ce6536498d4f2825e5cca255beef2e69f50697213143f676222b9660630073e9ccda29e5c4edafc7f7805e060da5936c172d3c3cc5512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
